#pragma once


#define RGBLIGHT_LIMIT_VAL 160
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 96
#define RGBLIGHT_DEFAULT_SPD 128
#define ONBOARD_LED_PIN GP13
